apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tmpchart.fullname" . }}-secret
  annotations:
{{- if .Values.providedPassword }}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
{{- else }}
    "helm.sh/hook": "pre-install,pre-rollback"
{{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  my-password: {{ .Values.providedPassword | default (randAlphaNum 15) | toString | b64enc | quote }}
